# Generated by Django 6.0.7 on 2026-09-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('csex', models.CharField(default='F', max_length=1)),
                ('cbirthday', models.DateField(blank=True, null=True)),
                ('cemail', models.CharField(max_length=100)),
                ('cphone', models.CharField(max_length=50)),
                ('caddr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'myapp_student',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cID', models.ForeignKey(db_column='cID_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'db_table': 'myapp_permissions',
            },
        ),
    ]
